Repository Rpc-h/RPCh, pull requests merged in 2023-08, with the labels that each got.

#475 add quota columns
  .changeset/short-owls-invent.md
  .github/workflows/review.yml
  README.md
  apps/availability-monitor/package.json
  apps/availability-monitor/src/reviewer.spec.ts
  apps/discovery-platform/migrations/1691073458902_quota-sums.sql
  apps/discovery-platform/package.json
  apps/discovery-platform/src/client/index.spec.ts
  apps/discovery-platform/src/client/index.ts
  apps/discovery-platform/src/db/index.spec.ts
  apps/discovery-platform/src/db/index.ts
  apps/discovery-platform/src/entry-server/index.spec.ts
  apps/discovery-platform/src/entry-server/routers/v1/index.spec.ts
  apps/discovery-platform/src/entry-server/routers/v1/index.ts
  apps/discovery-platform/src/entry-server/routers/v1/middleware.spec.ts
  apps/discovery-platform/src/entry-server/routers/v1/middleware.ts
  apps/discovery-platform/src/quota/index.spec.ts
  apps/discovery-platform/src/quota/index.ts
  apps/discovery-platform/src/registered-node/index.spec.ts
  apps/discovery-platform/src/types/client.ts
  apps/funding-service/migrations/1676989506015_initial-fs.sql
  apps/funding-service/package.json
  apps/funding-service/src/access-token/index.spec.ts
  apps/funding-service/src/db/index.spec.ts
  apps/funding-service/src/db/index.ts
  apps/funding-service/src/entry-server/index.spec.ts
  apps/funding-service/src/entry-server/middleware/index.spec.ts
  apps/funding-service/src/queue/index.spec.ts
  apps/funding-service/src/request/index.spec.ts
  apps/funding-service/src/types/access-token.ts
  package.json
  packages/common/package.json
  packages/common/src/fixtures.ts
  packages/common/src/internal/db.spec.ts
  packages/common/src/internal/db.ts
  turbo.json
  yarn.lock
Labels: enhancement

#478 remove external HOPRd api endpoints
  .changeset/shiny-rice-cheat.md
  apps/availability-monitor/src/review/check.ts
  apps/discovery-platform/src/constants.ts
  apps/discovery-platform/src/entry-server/routers/v1/index.ts
  apps/discovery-platform/src/utils/index.ts
  devkit/manager/src/index.ts
  devkit/manager/src/tasks/register-nodes.ts
  devkit/sandbox/src/.env
  devkit/sandbox/src/central-docker-compose.yml
  devkit/sandbox/src/common.sh
  turbo.json
Labels: bug

#484 Adapt changes to providence
  apps/exit-node/.env
  apps/exit-node/.env-hoprd-default
  apps/exit-node/.env-hoprd.template
  apps/exit-node/.env-rpch-default
  apps/exit-node/.env-rpch.template
  apps/exit-node/docker-compose.yml
Labels: enhancement, devops

#487 specify publish config
  packages/common/package.json
  packages/ethereum-provider/package.json
  packages/ethers/package.json
  packages/sdk/package.json
Labels: enhancement
