Repository Rpc-h/RPCh, pull requests merged in 2023-05, with the labels that each got.

#386 Fix incorrect segmentation for non-ASCII characters
  packages/common/src/utils/index.spec.ts
  packages/common/src/utils/index.ts
Labels: bug, enhancement

#395 Force entry nodes and exit nodes
  apps/discovery-platform/README.md
  apps/discovery-platform/src/db/index.ts
  apps/discovery-platform/src/index.ts
  apps/exit-node/.env
  apps/exit-node/README.md
  apps/exit-node/src/index.ts
  apps/funding-service/.env
  apps/funding-service/README.md
  apps/rpc-server/.env
  apps/rpc-server/README.md
  apps/rpc-server/src/constants.ts
  apps/rpc-server/src/index.ts
  devkit/sandbox/src/.env
  devkit/sandbox/src/central-docker-compose.yml
  packages/sdk/src/index.spec.ts
  packages/sdk/src/index.ts
  turbo.json
Labels: enhancement

#403 Add more loadtests
  .gitignore
  apps/discovery-platform/README.md
  apps/discovery-platform/src/db/index.ts
  apps/discovery-platform/src/index.ts
  apps/exit-node/.env
  apps/exit-node/README.md
  apps/exit-node/src/index.ts
  apps/funding-service/.env
  apps/funding-service/README.md
  apps/rpc-server/.env
  apps/rpc-server/README.md
  apps/rpc-server/src/constants.ts
  apps/rpc-server/src/index.ts
  apps/rpc-server/src/server.ts
  devkit/loadtesting-k6/.eslintrc.js
  devkit/loadtesting-k6/README.md
  devkit/loadtesting-k6/package.json
  devkit/loadtesting-k6/src/discovery-platform/artificial.js
  devkit/loadtesting-k6/src/rpc-server/artificial.js
  devkit/loadtesting-k6/src/rpc-server/burst.js
  devkit/loadtesting-k6/src/rpc-server/constant.js
  devkit/loadtesting-k6/src/rpc-server/long.js
  devkit/loadtesting-k6/src/rpc-server/usage-blockwallet.js
  devkit/loadtesting-k6/src/rpc-server/usage-trustwallet.js
  devkit/sandbox/src/.env
  devkit/sandbox/src/central-docker-compose.yml
  packages/sdk/src/index.spec.ts
  packages/sdk/src/index.ts
  turbo.json
Labels: enhancement

#405 improve WS class
  packages/common/src/hoprd.ts
  packages/common/src/utils/index.ts
  packages/common/src/ws-helper.spec.ts
  packages/common/src/ws-helper.ts
  packages/sdk/src/index.ts
Labels: bug
