Repository Rpc-h/RPCh, pull requests merged in 2023-03, with the labels that each got.

#277 update hoprd version and sandbox pluto
  apps/exit-node/.env
  devkit/sandbox/src/.env
  devkit/sandbox/src/nodes-docker-compose.yml
Labels: enhancement

#292 TSDocs for ethers
  packages/ethers/src/index.ts
  packages/ethers/src/utils.ts
Labels: documentation

#302 test free-disk-space
  .github/actions/build-rpch/action.yml
Labels: bug

#255 Add error message response to rpc-server
  apps/rpc-server/src/index.spec.ts
  apps/rpc-server/src/index.ts
Labels: enhancement

#251 Add retry capability when selecting entry node
  apps/discovery-platform/src/funding-service-api/index.ts
  packages/sdk/src/index.spec.ts
  packages/sdk/src/index.ts
Labels: enhancement

#279 Update images from alpine to bullseye-slim
  apps/discovery-platform/Dockerfile
  apps/exit-node/Dockerfile
  apps/exit-node/docker-compose.yml
  apps/funding-service/Dockerfile
  apps/rpc-server/Dockerfile
  devkit/manager/Dockerfile
  devkit/sandbox/src/nodes-docker-compose.yml
Labels: enhancement

#309 sdk code hygiene
  packages/sdk/src/index.spec.ts
  packages/sdk/src/index.ts
  packages/sdk/src/reliability-score.spec.ts
  packages/sdk/src/reliability-score.ts
Labels: enhancement
