Repository Rpc-h/RPCh, pull requests merged in 2023-04, with the labels that each got.

#263 Add metrics to dp and fs
  apps/discovery-platform/METRICS.md
  apps/discovery-platform/package.json
  apps/discovery-platform/src/constants.ts
  apps/discovery-platform/src/entry-server/index.spec.ts
  apps/discovery-platform/src/entry-server/index.ts
  apps/discovery-platform/src/entry-server/routers/v1/index.spec.ts
  apps/discovery-platform/src/entry-server/routers/v1/index.ts
  apps/discovery-platform/src/index.ts
  apps/discovery-platform/src/metric/index.ts
  apps/funding-service/METRICS.md
  apps/funding-service/package.json
  apps/funding-service/src/constants.ts
  apps/funding-service/src/entry-server/index.spec.ts
  apps/funding-service/src/entry-server/index.ts
  apps/funding-service/src/entry-server/middleware/index.ts
  apps/funding-service/src/index.ts
  apps/funding-service/src/metric/index.ts
  apps/funding-service/src/queue/index.spec.ts
  apps/funding-service/src/queue/index.ts
  yarn.lock
Labels: enhancement

#316 Internal commons
  apps/discovery-platform/package.json
  apps/discovery-platform/src/client/index.spec.ts
  apps/discovery-platform/src/constants.ts
  apps/discovery-platform/src/db/index.spec.ts
  apps/discovery-platform/src/db/index.ts
  apps/discovery-platform/src/entry-server/index.spec.ts
  apps/discovery-platform/src/entry-server/index.ts
  apps/discovery-platform/src/entry-server/routers/v1/index.spec.ts
  apps/discovery-platform/src/entry-server/routers/v1/index.ts
  apps/discovery-platform/src/funding-request/index.spec.ts
  apps/discovery-platform/src/funding-service-api/index.spec.ts
  apps/discovery-platform/src/index.ts
  apps/discovery-platform/src/metric/index.ts
  apps/discovery-platform/src/quota/index.spec.ts
  apps/discovery-platform/src/registered-node/index.spec.ts
  apps/funding-service/package.json
  apps/funding-service/src/access-token/index.spec.ts
  apps/funding-service/src/constants.ts
  apps/funding-service/src/db/index.spec.ts
  apps/funding-service/src/db/index.ts
  apps/funding-service/src/entry-server/index.spec.ts
  apps/funding-service/src/entry-server/index.ts
  apps/funding-service/src/entry-server/middleware/index.spec.ts
  apps/funding-service/src/index.ts
  apps/funding-service/src/metric/index.ts
  apps/funding-service/src/queue/index.spec.ts
  apps/funding-service/src/queue/index.ts
  apps/funding-service/src/request/index.spec.ts
  packages/common/package.json
  packages/common/src/internal/db.ts
  packages/common/src/internal/metric-manager.ts
  yarn.lock
Labels: enhancement

#319 Fix exit-node Docker Compose
  apps/exit-node/docker-compose.yml
  devkit/sandbox/src/.env
Labels: bug

#318 Exit node metrics
  apps/exit-node/.env
  apps/exit-node/METRICS.md
  apps/exit-node/docker-compose.yml
  apps/exit-node/package.json
  apps/exit-node/src/constants.ts
  apps/exit-node/src/index.spec.ts
  apps/exit-node/src/index.ts
  apps/funding-service/src/access-token/index.spec.ts
  devkit/sandbox/src/nodes-docker-compose.yml
  packages/common/src/cache.ts
  turbo.json
Labels: enhancement

#315 Rename identityDir to identityFile
  apps/exit-node/.env
  apps/exit-node/README.md
  apps/exit-node/docker-compose.yml
  apps/exit-node/src/constants.ts
  apps/exit-node/src/identity.spec.ts
  apps/exit-node/src/identity.ts
  apps/exit-node/src/index.spec.ts
  apps/exit-node/src/index.ts
  turbo.json
Labels: enhancement

#312 Manager - Code Hygiene
  apps/discovery-platform/package.json
  apps/funding-service/Dockerfile
  apps/funding-service/package.json
  apps/funding-service/src/blockchain/erc20-fixture.json
  apps/funding-service/src/entry-server/index.ts
  apps/funding-service/src/index.ts
  apps/funding-service/src/queue/index.spec.ts
  apps/funding-service/src/queue/index.ts
  devkit/manager/package.json
  devkit/manager/src/index.ts
  devkit/manager/src/tasks/register-hoprd-nodes.ts
  devkit/manager/src/utils.ts
  packages/common/hardhat.config.ts
  packages/common/package.json
  packages/common/src/blockchain.spec.ts
  packages/common/src/blockchain.ts
  packages/common/src/constants.ts
  packages/common/src/erc20-fixture.ts
  packages/common/src/index.ts
  packages/common/tsconfig.json
  yarn.lock
Labels: enhancement

#329 replace crypto-bridge with new crypto libs
  apps/exit-node/package.json
  apps/exit-node/src/identity.ts
  apps/exit-node/src/index.ts
  apps/rpc-server/package.json
  apps/rpc-server/src/index.ts
  devkit/e2e/package.json
  devkit/e2e/src/e2e.spec.ts
  packages/common/package.json
  packages/common/src/fixtures.ts
  packages/common/src/request.spec.ts
  packages/common/src/request.ts
  packages/common/src/response.spec.ts
  packages/common/src/response.ts
  packages/crypto-bridge/.eslintrc.js
  packages/crypto-bridge/.gitignore
  packages/crypto-bridge/.prettierrc.js
  packages/crypto-bridge/CHANGELOG.md
  packages/crypto-bridge/README.md
  packages/crypto-bridge/jest.config.js
  packages/crypto-bridge/package.json
  packages/crypto-bridge/src/index.spec.ts
  packages/crypto-bridge/src/index.ts
  packages/crypto-bridge/src/nodejs/index.ts
  packages/crypto-bridge/src/web/index.ts
  packages/crypto-bridge/tsconfig.json
  packages/crypto-bridge/tsup.config.js
  packages/ethers/package.json
  packages/ethers/src/index.spec.ts
  packages/ethers/src/index.ts
  packages/sdk/package.json
  packages/sdk/src/index.mock.ts
  packages/sdk/src/index.spec.ts
  packages/sdk/src/index.ts
  turbo.json
  yarn.lock
Labels: enhancement

#330 use new cross-fetch
  packages/common/package.json
  packages/sdk/package.json
  packages/sdk/src/index.ts
  yarn.lock
Labels: enhancement

#345 Disable funding service from sandbox
  devkit/sandbox/src/central-docker-compose.yml
Labels: enhancement

#353 Use compression in request and response, unit tests updated (2/2)
  .gitignore
  apps/exit-node/src/index.spec.ts
  apps/exit-node/src/index.ts
  configs/tsup/index.js
  devkit/sandbox/src/common.sh
  devkit/sandbox/src/nodes-docker-compose.yml
  packages/common/package.json
  packages/common/src/cache.spec.ts
  packages/common/src/compression/compression-samples.ts
  packages/common/src/compression/debugger.ts
  packages/common/src/compression/dictionaries.ts
  packages/common/src/compression/index.spec.ts
  packages/common/src/compression/index.ts
  packages/common/src/fixtures.ts
  packages/common/src/message.ts
  packages/common/src/request.spec.ts
  packages/common/src/request.ts
  packages/common/src/response.spec.ts
  packages/common/src/response.ts
  packages/common/src/segment.spec.ts
  packages/common/src/segment.ts
  packages/common/src/types/compression.ts
  packages/common/src/utils/index.spec.ts
  packages/common/src/utils/index.ts
  packages/sdk/src/index.mock.ts
  packages/sdk/src/index.spec.ts
  packages/sdk/src/index.ts
  packages/sdk/src/request-cache.spec.ts
  yarn.lock
Labels: enhancement

#300 Start sdk in ethers send function
  packages/ethereum-provider/src/index.ts
  packages/ethers/src/index.spec.ts
  packages/ethers/src/index.ts
  packages/sdk/src/index.ts
Labels: enhancement

#364 remove old metrics
  apps/exit-node/src/exit.ts
  apps/funding-service/src/queue/index.ts
  apps/funding-service/src/request/index.ts
  package.json
  packages/common/src/cache.ts
  packages/common/src/utils/logger.ts
  packages/ethereum-provider/src/index.ts
  packages/ethers/src/index.ts
  packages/sdk/src/index.ts
  packages/sdk/src/reliability-score.ts
Labels: enhancement

#367 catch WS errors
  packages/common/src/hoprd.ts
Labels: bug

#371 back merge v0.1.7
  apps/rpc-server/src/index.spec.ts
  apps/rpc-server/src/index.ts
  devkit/sandbox/src/common.sh
  packages/common/src/hoprd.spec.ts
  packages/common/src/hoprd.ts
  packages/ethereum-provider/package.json
  packages/sdk/src/index.ts
  yarn.lock
Labels: enhancement

#384 setup infinite retry on message listener
  apps/exit-node/src/index.spec.ts
  apps/exit-node/src/index.ts
  apps/rpc-server/src/index.spec.ts
  packages/common/src/fixtures.ts
  packages/common/src/hoprd.spec.ts
  packages/common/src/hoprd.ts
  packages/common/src/utils/index.spec.ts
  packages/common/src/utils/index.ts
  packages/sdk/src/index.spec.ts
  packages/sdk/src/index.ts
Labels: bug, enhancement
